/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author juanm
 */
public class PanelMenuEliminar extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuEliminar
     */
    public PanelMenuEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCampoBuscar = new javax.swing.JPanel();
        nombreBusqueda = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();

        nombreBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreBusqueda.setText("Ingrese el nombre a buscar:");

        campoBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        botonEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCampoBuscarLayout = new javax.swing.GroupLayout(panelCampoBuscar);
        panelCampoBuscar.setLayout(panelCampoBuscarLayout);
        panelCampoBuscarLayout.setHorizontalGroup(
            panelCampoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoBuscarLayout.createSequentialGroup()
                .addComponent(nombreBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonEliminar))
        );
        panelCampoBuscarLayout.setVerticalGroup(
            panelCampoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoBuscarLayout.createSequentialGroup()
                .addGroup(panelCampoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda)
                    .addComponent(nombreBusqueda)
                    .addComponent(botonEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelCampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(Crud.estaCandidato(App.candidatos, campoBusqueda.getText())) {
            Crud.eliminarCandidato(App.candidatos, campoBusqueda.getText());
            JOptionPane.showMessageDialog(this.getRootPane(), "El candidato fue eliminado con exito", "Eliminar Candidato", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "El candidato no fue encontrado", "Eliminar Candidato", JOptionPane.WARNING_MESSAGE);
        }

        campoBusqueda.setText("");
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel nombreBusqueda;
    private javax.swing.JPanel panelCampoBuscar;
    // End of variables declaration//GEN-END:variables
}
