/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juanm
 */
public class PanelMenuResultado extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuResultado
     */
    public PanelMenuResultado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResultado = new javax.swing.JPanel();
        tituloGanador = new java.awt.Label();
        scrollCampoPromesas = new javax.swing.JScrollPane();
        campoPromesas = new javax.swing.JTextArea();
        tituloPromesas = new java.awt.Label();
        nombreGanador = new java.awt.Label();
        cedulaGanador = new java.awt.Label();
        tituloTop3 = new java.awt.Label();
        scrollCampoTop3 = new javax.swing.JScrollPane();
        campoTop3 = new javax.swing.JTextArea();
        tituloPartido = new java.awt.Label();
        scrollCampoPartido = new javax.swing.JScrollPane();
        CampoPartido = new javax.swing.JTextArea();

        tituloGanador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloGanador.setText("EL GANADOR ES:");

        campoPromesas.setColumns(20);
        campoPromesas.setRows(5);
        scrollCampoPromesas.setViewportView(campoPromesas);

        tituloPromesas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloPromesas.setText("Promesas:");

        nombreGanador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreGanador.setText("Nombre:");

        cedulaGanador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaGanador.setText("Cédula:");

        tituloTop3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloTop3.setText("TOP 3 CIUDADES CON MENOS CANDIDATOS");

        campoTop3.setColumns(20);
        campoTop3.setRows(5);
        scrollCampoTop3.setViewportView(campoTop3);

        tituloPartido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloPartido.setText("PARTIDO CON MÁS CANDIDATOS INSCRITOS");

        CampoPartido.setColumns(20);
        CampoPartido.setRows(5);
        scrollCampoPartido.setViewportView(CampoPartido);

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollCampoPromesas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(nombreGanador, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addComponent(tituloPromesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulaGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollCampoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollCampoTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addComponent(tituloGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nombreGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloPromesas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollCampoPromesas))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scrollCampoTop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollCampoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CampoPartido;
    private javax.swing.JTextArea campoPromesas;
    private javax.swing.JTextArea campoTop3;
    private java.awt.Label cedulaGanador;
    private java.awt.Label nombreGanador;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JScrollPane scrollCampoPartido;
    private javax.swing.JScrollPane scrollCampoPromesas;
    private javax.swing.JScrollPane scrollCampoTop3;
    private java.awt.Label tituloGanador;
    private java.awt.Label tituloPartido;
    private java.awt.Label tituloPromesas;
    private java.awt.Label tituloTop3;
    // End of variables declaration//GEN-END:variables
}
