/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juanm
 */
public class PanelMenuConteo extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuConteo
     */
    public PanelMenuConteo() {
        initComponents();
    }
    
    public void crearCampos() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloConteo = new javax.swing.JLabel();
        scrollMenuConteo = new javax.swing.JScrollPane();
        panelConteo = new javax.swing.JPanel();
        botonIngresar = new javax.swing.JButton();

        tituloConteo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloConteo.setText("Ingrese los votos para:");

        panelConteo.setLayout(new java.awt.GridLayout(2, 2, 30, 0));
        scrollMenuConteo.setViewportView(panelConteo);

        botonIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonIngresar.setText("Ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloConteo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(botonIngresar))
            .addComponent(scrollMenuConteo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloConteo)
                    .addComponent(botonIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollMenuConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPanel panelConteo;
    private javax.swing.JScrollPane scrollMenuConteo;
    private javax.swing.JLabel tituloConteo;
    // End of variables declaration//GEN-END:variables
}
